<?xml version="1.0" encoding="UTF-8"?>
<element name="gallery" xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  <attribute name="path"/>
  <optional>
    <attribute name="caption"/>
  </optional>
  <optional>
    <attribute name="width"/>
  </optional>
  <optional>
    <attribute name="ratio"/>
  </optional>
  <optional>
    <attribute name="nav">
      <choice>
        <value>thumbs</value>
      </choice>
    </attribute>
  </optional>
  <optional>
    <attribute name="autoplay">
      <data type="integer">
        <param name="minInclusive">0</param>
      </data>
    </attribute>
  </optional>
  <optional>
    <attribute name="fullscreen">
      <choice>
        <value>true</value>
        <value>native</value>
      </choice>
    </attribute>
  </optional>
  <optional>
    <attribute name="transition">
      <choice>
        <value>slide</value>
        <value>crossfade</value>
        <value>dissolve</value>
      </choice>
    </attribute>
  </optional>
  <zeroOrMore>
    <element name="pic">
      <attribute name="path"/>
      <optional>
        <attribute name="caption"/>
      </optional>
    </element>
  </zeroOrMore>
</element>
